version: '3.8'

services:
  # 1. Servidor de Base de Datos (Infraestructura)
  db:
    image: postgres:15
    container_name: cafetech_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: cafetech_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  # 2. Servidor de Aplicaciones (Backend)
  backend:
    build: 
      context: ./cafetech_server
    container_name: cafetech_backend
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=secret_password
      - DB_NAME=cafetech_db
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: always

  # 3. Aplicación WEB Desplegada (Frontend)
  frontend:
    build: 
      context: ./cafetech
    container_name: cafetech_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  # 4. Balanceo de Cargas, Dominio y Seguridad (NGINX)
  nginx:
    image: nginx:alpine
    container_name: cafetech_nginx_proxy
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS (Certificados de seguridad)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Aquí se montarían los certificados reales en producción:
      # - ./nginx/certs:/etc/nginx/certs:ro 
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  db_data:
